version: '3.5'

services:
  postgres:
    container_name: postgres_container
    image: postgres:18.1
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_pwd
      PGDATA: /data/postgres
      POSTGRES_DB: meas
    volumes:
      - postgres:/data/postgres
    restart: unless-stopped

  measurements:
    container_name: measurements_container
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgres:5432/meas
      QUARKUS_DATASOURCE_USERNAME: postgres_user
      QUARKUS_DATASOURCE_PASSWORD: postgres_pwd
    volumes:
      - measurements:/deployments
    restart: unless-stopped

networks:
  postgres-jvm:
    name: postgres-jvm-network
    driver: bridge

volumes:
  postgres:
  measurements:
